[package]
name = "orian_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "orian_nif"
crate-type = ["cdylib"]

[dependencies]
blake3 = "1.8"
bytes = "1"
futures-util = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
rustler = "0.38"
tokio = { version = "1", features = ["rt-multi-thread", "fs", "io-util", "macros", "sync"] }
tokio-util = { version = "0.7", features = ["io"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[profile.release]
lto = true
opt-level = 3
