name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.4"
          otp-version: "27.3"
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.16.0"
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y libc6-dev
      - run: mix deps.get && mix format --check-formatted && mix test
      - run: mix hex.build
